"""lion1

Revision ID: 23fa828faed0
Revises: fcff468f970d
Create Date: 2022-06-13 15:57:48.765176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa828faed0'
down_revision = 'fcff468f970d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
