"""kites

Revision ID: 594790afead3
Revises: c00baac04c55
Create Date: 2022-06-13 15:23:57.229602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594790afead3'
down_revision = 'c00baac04c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
