"""table

Revision ID: 5f46358a5029
Revises: d4c61d8784a3
Create Date: 2022-06-09 18:36:10.388153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f46358a5029'
down_revision = 'd4c61d8784a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profileImage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profileImage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
