"""lion1234

Revision ID: 997178d9b7f2
Revises: 23fa828faed0
Create Date: 2022-06-13 15:58:29.302366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997178d9b7f2'
down_revision = '23fa828faed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
