"""kites123

Revision ID: b59ff74172c5
Revises: af0514e2fba9
Create Date: 2022-06-13 15:48:17.164622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59ff74172c5'
down_revision = 'af0514e2fba9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
