"""votes

Revision ID: d7ef82ad4b8c
Revises: 997178d9b7f2
Create Date: 2022-07-05 14:06:51.287651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ef82ad4b8c'
down_revision = '997178d9b7f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
