"""everything-left

Revision ID: dc1607d69a55
Revises: 77f84678e0c7
Create Date: 2022-06-08 19:33:44.759012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1607d69a55'
down_revision = '77f84678e0c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=False))
    op.add_column('users', sa.Column('phoneNumber', sa.String(), nullable=False))
    op.add_column('users', sa.Column('profileImage', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phoneNumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profileImage')
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
